### ISSUE TITLE
Capture the source 🤔 

### ISSUE THREAD

**Issue by bepolymathe** [benjypng/logseq-quicktodo-plugin#14]
Hi @hkgnp 

When I used Emacs + org-mode there was a feature that I like and that is missing in Logseq. Maybe your plugin could fit it in ?
 
This is the functionality to indicate the source (context) of the capture([org-capture template](https://orgmode.org/manual/Template-expansion.html)). Suppose I am in the journal page `[[2022-12-09]]`, I am doing `mt` +type and I have a note or a task in my default page "Inbox". I will find it very useful to remember where I was when I captured it.

This is not a priority request obviously but I sometimes find it interesting to think about my work process that I thought of doing if or that according to a context around. A kind of "thinking backlink" rather than the contents of the note.
 
Have a nice day.

**Comment by benjypng** [comment]
Thanks for the suggestion. But I’m not sure what you are describing 😂Could you use an example?Regards,ben On 9 Dec 2022, at 3:51 PM, bepolymathe ***@***.***> wrote:﻿
Hi @hkgnp
When I used Emacs + org-mode there was a feature that I like and that is missing in Logseq. Maybe your plugin could fit it in ?
This is the functionality to indicate the source (context) of the capture(org-capture template). Suppose I am in the journal page [[2022-12-09]], I am doing mt +type and I have a note or a task in my default page "Inbox". I will find it very useful to remember where I was when I captured it.
This is not a priority request obviously but I sometimes find it interesting to think about my work process that I thought of doing if or that according to a context around. A kind of "thinking backlink" rather than the contents of the note.
Have a nice day.

**Comment by bepolymathe** [comment]
Yes sorry it was not very clear !

The idea is this. When I capture a note or a todo thanks to your plugin I would like to know the place where I was in Logseq at the time of this capture via a block or page reference.

# first step (capture)

![image](https://user-images.githubusercontent.com/29939805/206661884-c2aa6c89-41bb-49f8-98e7-105dc27b6234.png)

# second step (include mention in daily log)

![image](https://user-images.githubusercontent.com/29939805/206663753-f2d090f2-0467-45ef-a5dc-28ccdaf0f8c3.png)

# third step (task include in inbox with block ref to source) 

![image](https://user-images.githubusercontent.com/29939805/206663234-50d0c3b9-f2c5-400e-ab9b-f051ea024ace.png)

# fourth step (after scheduled task to another date ref to origin still there) 

![image](https://user-images.githubusercontent.com/29939805/206663472-9a612608-3370-462d-b1e5-6f48d5a5f43e.png)

**Comment by bepolymathe** [comment]
One could imagine a variant that simply refers to the page and not a specific block... if the user does not wish to integrate the mention of the capture into the page where he is at the time of capture.

**Comment by jaker-dotcom** [comment]
Couldn't you just write whatever you want, copy block reference / embed (ctrl+c/e while in editing mode) and then m -> t and paste the reference? 
If you want, you could later go to the reference and with the logseq-swapblocks-plugin exchange the original and the reference. 

Not exactly the same but I think it works quite well.

**Comment by benjypng** [comment]
Available in the latest version.
